20170328prework/Models/ReportModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _20170328prework.Models
{
    public class ReportModel
    {
        public string RecId { get; set; }
        public string Subject { get; set; }
        public int LikeCount { get; set; }
    }
}

20170328prework/ViewModels/SearchActionModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _20170328prework.ViewModels
{
    public class SearchActionModel
    {
        public string Name { get; set; }
        public string PhoneNumber { get; set; }
    }
}

20170328prework/ViewModels/TestActionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _20170328prework.ViewModels
{
    public class TestActionViewModel
    {
        public string Test { get; set; }
        public string PhoneNumber { get; set; }
    }
}

20170328prework/ViewModels/ToolBarViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace _20170328prework.ViewModels
{
    public class ToolBarViewModel
    {
        public string ControllerName { get; set; }

        public bool? DisSearch { get; set; }
        public bool? DisNew { get; set; }
        public bool? DisDelete { get; set; }
        public bool? DisCheck { get; set; }
        public bool? DisFailed { get; set; }
        public bool? DisAttach { get; set; }
    }
}

20170328prework/Controllers/HomeController.cs
using _20170328prework.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Runtime.Caching;

namespace _20170328prework.Controllers
{
    public class HomeController : Controller
    {
        private static ObjectCache _Cache = MemoryCache.Default;
        private static object _LockObj = new object();

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Search()
        {
            var cacheData = _Cache["Home"];
            var viewModel = new SearchActionModel();

            try
            {
                viewModel = cacheData as SearchActionModel;
                if(viewModel == null)
                {
                    viewModel = new SearchActionModel();
                    viewModel.Name = String.Empty;
                    viewModel.PhoneNumber = String.Empty;
                }
            }
            catch
            {
                viewModel = new SearchActionModel();
                viewModel.Name = String.Empty;
                viewModel.PhoneNumber = String.Empty;
            }


            return PartialView(viewModel);
        }

        public void GoSearch(SearchActionModel actionModel)
        {
            CacheItemPolicy cachePolicy = new CacheItemPolicy();
            cachePolicy.AbsoluteExpiration = DateTime.Now.AddMinutes(20);

            lock (_LockObj)
            {
                _Cache.Set("Home", actionModel, cachePolicy);
            }
        }

        public ActionResult Add()
        {
            return PartialView("_Add");
        }

        public ActionResult Check()
        {
            return View();
        }

    }
}

20170328prework/Controllers/PrintController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Printing;
using System.Diagnostics;
using _20170328prework.Reports;
using _20170328prework.Database;
using Microsoft.Reporting.WebForms;
using _20170328prework.Models;

namespace _20170328prework.Controllers
{
    public class PrintController : Controller
    {
        // GET: Print
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ReportPrint()
        {
            //var db = new HomePageEntities();
            //var entityList = db.ForumArticle.ToList();

            //IList<ReportModel> reportList = new List<ReportModel>();
            //foreach (var item in entityList)
            //{
            //    var tmp = new ReportModel();
            //    tmp.RecId = item.RecId.ToString();
            //    tmp.Subject = item.Subject;
            //    tmp.LikeCount = item.LikeCount.Value;

            //    reportList.Add(tmp);
            //}

            IList<ReportModel> reportList = new List<ReportModel>();
            reportList.Add(new ReportModel()
            {
                RecId = "1",
                Subject = "Test",
                LikeCount = 20
            });

            reportList.Add(new ReportModel()
            {
                RecId = "2",
                Subject = "Test2",
                LikeCount = 10
            });

            reportList.Add(new ReportModel()
            {
                RecId = "3",
                Subject = "Test3",
                LikeCount = 24
            });

            try
            {
                var result = new service.Report(Server.MapPath("~/Reports/Report1.rdlc"), "test", reportList, service.Report.Type.PDF);
                return File(result.Content, result.MimeType);
            }
            catch
            {
                throw;
            }


        }

    }
}

20170328prework/Controllers/TestController.cs
using _20170328prework.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Caching;
using System.Web;
using System.Web.Mvc;

namespace _20170328prework.Controllers
{
    public class TestController : Controller
    {
        private static ObjectCache _Cache = MemoryCache.Default;
        private static object _LockObj = new object();

        // GET: Test
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Search()
        {
            var cacheData = _Cache["Test"];
            var viewModel = new TestActionViewModel();

            try
            {
                viewModel = cacheData as TestActionViewModel;
                if (viewModel == null)
                {
                    viewModel = new TestActionViewModel();
                    viewModel.Test = String.Empty;
                    viewModel.PhoneNumber = String.Empty;
                }
            }
            catch
            {
                viewModel = new TestActionViewModel();
                viewModel.Test = String.Empty;
                viewModel.PhoneNumber = String.Empty;
            }


            return PartialView(viewModel);
        }

        public void GoSearch(TestActionViewModel actionModel)
        {
            CacheItemPolicy cachePolicy = new CacheItemPolicy();
            cachePolicy.AbsoluteExpiration = DateTime.Now.AddMinutes(20);

            lock (_LockObj)
            {
                _Cache.Set("Test", actionModel, cachePolicy);
            }
        }

        public ActionResult Add()
        {
            return PartialView("_Add");
        }

        public ActionResult Check()
        {
            return View();
        }
    }
}

20170328prework/Controllers/ToolBarController.cs
using _20170328prework.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace _20170328prework.Controllers
{
    public class ToolBarController : Controller
    {
        // GET: ToolBar
        public ActionResult ToolBar(string controllerName)
        {
            if(String.IsNullOrEmpty(controllerName))
            {
                return RedirectToAction("Index", "Home");
            }

            //TODO: 登入身分檢核

            var viewModel = new ToolBarViewModel();
            viewModel.ControllerName = controllerName;
            viewModel.DisCheck = true;
            return PartialView("_ToolBar", viewModel);
        }
    }
}

20170328prework/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<div id="toolbar" class="row">

</div>

<p>Use this area to provide additional information.</p>

@section Scripts{
    <script src="~/Scripts/ToolBarScripts.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            InitToolBar("toolbar", "Home");
        })
    </script>
}

20170328prework/Views/Home/Check.cshtml
@{
    ViewBag.Title = "Check";
}

<h2>Check</h2>

20170328prework/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>
<div id="toolbar" class="row">

</div>
<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>
@section Scripts{
    <script src="~/Scripts/ToolBarScripts.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            InitToolBar("toolbar", "Home");
        })
    </script>
}

20170328prework/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>
<div id="toolbar">

</div>
<section id="display">
    <div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-3">
            <button type="button" class="btn btn-danger" onclick="CloseAddFun()">關閉新增功能</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-danger" onclick="CloseAddandSearchFun()">關閉新增及搜尋功能</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-danger" onclick="CloseAttachFun()">關閉附件功能</button>
        </div>
        <div class="col-md-3">
            <button type="button" class="btn btn-danger" onclick="CloseDelFun()">關閉刪除功能</button>
        </div>
    </div>
</section>


@section Scripts{
    <script src="~/Scripts/ToolBarScripts.js" type="text/javascript"></script>
    <script src="~/Scripts/validator.js" type="text/javascript"></script>
    <script src="~/Scripts/customvalidate.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            InitToolBar("toolbar", "Home");

        })

        function GoSearch() {
            $.ajax({
                type: 'post',
                url: '@Url.Action("GoSearch","Home")',
                data: {
                    Name: $('#Name').val(),
                    PhoneNumber: $('#PhoneNumber').val()
                },
                success: function (result) {
                    $('#searchpanel').html(result);
                    $('#myModal').modal('hide');
                },
                error: function () {
                    $('#searchpanel').html('<h1>查詢失敗！</h1>')
                }
            })
        };

        function CloseAddFun() {
            //各自依據取到的資料調整toolbar狀態
            ToolBarStateChange(false, true, false, false, false, false);
        };

        function CloseAddandSearchFun() {
            ToolBarStateChange(true, true, false, false, false, false);
        };

        function CloseAttachFun() {
            ToolBarStateChange(false, false, false, false, false, true);
        };

        function CloseDelFun() {
            ToolBarStateChange(false, false, false, true, false, false);
        };
    </script>
}

20170328prework/Views/Home/Search.cshtml
@model _20170328prework.ViewModels.SearchActionModel

<h2>Home Search View</h2>
<form class="form" id="searchform">
    <div class="form-group has-feedback">
        <label class="control-label">姓名</label>
        <input type="text" class="form-control" placeholder="請輸入姓名" id="Name" value="@Model.Name" required data-required-error="此欄位要輸入喔^.<" data-equals data-cusmin="2" data-cusmax="10" />
        <div class="help-block with-errors"></div>
    </div>
    
    <div class="form-group has-feedback">
        <label class="control-label">電話</label>
        <input type="text" class="form-control" placeholder="請輸入電話" id="PhoneNumber" value="@Model.PhoneNumber" />
    </div>
    <div class="form-group">
        <button onclick="GoSearch()" class="btn btn-primary">查詢</button>
    </div>
</form>

20170328prework/Views/Home/_Add.cshtml
<form class="form" role="form" id="homeadd">
    <div class="form-group">
        <label class="control-label">姓名</label>
        <input type="text" class="form-control" placeholder="請輸入姓名" required data-required-error="此欄位要輸入喔^.<" data-equals data-cusmin="2" data-cusmax="10" />
        <div class="help-block with-errors"></div>
    </div>
    <div class="form-group">
        <label class="control-label">手機號碼</label>
        <input type="text" class="form-control" placeholder="請輸入手機號碼" 
               pattern="^[0-9]*$" required data-required-error="此欄位要輸入喔^.<" data-pattern-error="請輸入數字喔" data-minlength="10" data-minlength-error="手機號碼有10個數字!" />
        <div class="help-block with-errors"></div>
    </div>
    <div class="form-group">
        <label class="control-label">地址</label>
        <input type="text" class="form-control" placeholder="請輸入地址" />
    </div>
    <div>
        <button type="submit" class="btn btn-success">送出</button>
    </div>
</form>

20170328prework/Views/Print/Index.cshtml
<form role="form">
    <div>
        <select id="bank">
            <option value="A">A銀行</option>
            <option value="B">B銀行</option>
        </select>
    </div>
    <div class="form-group">
        <label class="control-label">姓名</label>
        <input type="text" id="username" class="form-control" value="Ray" />
        <label>x-座標</label>
        <input type="text" id="username-xaxis" value="430" />
        <label>y-座標</label>
        <input type="text" id="username-yaxis" value="110" />
    </div>
    <div class="form-group">
        <label class="control-label">金額</label>
        <input type="text" class="form-control" id="money" value="1000000" style="margin-bottom:5px;" />
        <label>x-座標</label>
        <input type="text" id="money-xasix" value="80" />
        <label>y-座標</label>
        <input type="text" id="money-yasix" value="100" />
    </div>
    <div class="form-group">
        <label class="control-label">備註</label>
        <input type="text" class="form-control" />
    </div>
    <div class="form-group">
        <label class="control-label">日期</label>
        <input class="form-control" value="@DateTime.Now.ToString("yyyy/MM/dd")" id="time" />
    </div>
</form>

<div class="row">
    <button type="button" id="previewbtn" onclick="DrawCanvas()" class="btn btn-info">預覽</button>
    <button type="button" id="print" onclick="Print()" class="btn btn-danger">列印</button>
</div>

<div class="row">
    <canvas id="preview" style="border:1px solid #d3d3d3;background:#ffffff;"></canvas>
</div>


<img src="~/Images/money-1.jpg" id="abank" class="hidden" />
<img src="~/Images/money-2.jpg" id="bbank" class="hidden" />
<div id="viewpanel">
    <img src="~/Images/emma_s.jpg" id="test" class="hidden" />
</div>
<canvas id="printcanvas" width="700" height="400" class="hidden"></canvas>

@section Scripts{
    <script type="text/javascript">
        $(document).ready(function () {
        });

        function DrawCanvas() {
            var canvas = document.getElementById('preview');
            var bank = $('#bank').val();
            var ctx = canvas.getContext("2d");
            if (bank == 'A') {
                $('#preview').prop('width', 600);
                $('#preview').prop('height', 283);
                var img = document.getElementById("abank")
                ctx.drawImage(img, 0, 0)
            }
            else {
                $('#preview').prop('width', 600);
                $('#preview').prop('height', 280);
                ctx.drawImage(document.getElementById("bbank"), 0, 0)
            }
            ctx.font = "30px Arial";
            console.log($('#username').val());
            ctx.fillText($('#username').val(), $('#username-xaxis').val(), $('#username-yaxis').val());
            ctx.font = "24px Arial";
            ctx.fillText($('#money').val(), $('#money-xasix').val(), $('#money-yasix').val());
            ctx.font = "16px Arial";
            ctx.fillText($('#time').val(), 400, 55);
            
        }

        function Print() {

            $.ajax({
                type: 'post',
                url: '@Url.Action("PrintCheque","Print")',
                data: {

                }
            })

            //var canvas = document.getElementById('printcanvas');
            //var ctx = canvas.getContext("2d");

            //ctx.font = "30px Arial";
            //console.log($('#username').val());
            //ctx.fillText($('#username').val(), 80, 110);
            //ctx.font = "24px Arial";
            //ctx.fillText($('#money').val(), 430, 110);
            //ctx.font = "16px Arial";
            //ctx.fillText($('#time').val(), 400, 55);

            //var img = document.getElementById("test");
            //img.src = canvas.toDataURL();


            //var printContent = document.getElementById('viewpanel');/*取得要列印的區域*/
            //var windowUrl = 'about:blank';
            //var uniqueName = new Date();
            //var windowName = 'Print' + uniqueName.getTime();
            //var printWindow = window.open(windowUrl, windowName);

            //printWindow.document.write(printContent.innerHTML);
            //printWindow.document.close();
            //printWindow.focus();
            //printWindow.print();
            //printWindow.close();
        }
    </script>
}

20170328prework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - 我的 ASP.NET 應用程式</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("應用程式名稱", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("首頁", "Index", "Home")</li>
                    <li>@Html.ActionLink("關於", "About", "Home")</li>
                    <li>@Html.ActionLink("Test", "Index", "Test")</li>
                    <li>@Html.ActionLink("Print", "Index", "Print")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        <input type="hidden" id="toolpath" value="@Url.Action("ToolBar", "ToolBar")" />
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 我的 ASP.NET 應用程式</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

20170328prework/Views/Test/Check.cshtml
@{
    ViewBag.Title = "Check";
}

<h2>Test Check</h2>

20170328prework/Views/Test/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<div id="toolbar" class="row">

</div>
<div id="display">
    <ol>
        <li>
            使用InitToolBar傳入指定位置的div以及controller name建立ToolBar
        </li>
        <li>
            action名稱需固定
        </li>
        <li>
            若使用ajax，則回傳的partiview對應的位置id需固定
        </li>
    </ol>
</div>

@section Scripts{
    <script src="~/Scripts/ToolBarScripts.js" type="text/javascript"></script>
    <script src="~/Scripts/validator.js" type="text/javascript"></script>
    <script src="~/Scripts/customvalidate.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            InitToolBar("toolbar", "Test");
        });

        function GoSearch() {
            $.ajax({
                type: 'post',
                url: '@Url.Action("GoSearch","Test")',
                data: {
                    Test: $('#Test').val(),
                    PhoneNumber: $('#PhoneNumber').val()
                },
                success: function (result) {
                    $('#searchpanel').html(result);
                    $('#myModal').modal('hide');
                },
                error: function () {
                    $('#searchpanel').html('<h1>查詢失敗！</h1>')
                }
            })
        };
    </script>
}

20170328prework/Views/Test/Search.cshtml
@model _20170328prework.ViewModels.TestActionViewModel

<h2>Test Search View</h2>

<form class="form has-feedback" id="testform" role="form">
    <div class="form-group">
        <label class="control-label">測試</label>
        <input type="text" class="form-control" placeholder="請輸入測試" id="Test" value="@Model.Test" required data-required-error="測試也是要填啊!" data-equals data-cusmin="5" data-cusmax="20" />
        <div class="help-block with-errors"></div>
    </div>
    <div class="form-group">
        <label class="control-label">電話</label>
        <input type="text" class="form-control" placeholder="請輸入電話" id="PhoneNumber" value="@Model.PhoneNumber" required />
    </div>
    <div class="form-group">
        <button onclick="GoSearch()" class="btn btn-primary">查詢</button>
    </div>
</form>

20170328prework/Views/Test/_Add.cshtml
<form class="form" role="form">
    <div class="form-group">
        <label class="control-label">123</label>
        <input type="text" class="form-control" placeholder="請輸入123" />
    </div>
    <div class="form-group">
        <label class="control-label">456</label>
        <input type="text" class="form-control" placeholder="請輸入456" />
    </div>
    <div class="form-group">
        <label class="control-label">789</label>
        <input type="text" class="form-control" placeholder="請輸入789" />
    </div>
    <div>
        <button type="submit" class="btn btn-success">送出</button>
    </div>
</form>

20170328prework/Views/ToolBar/_ToolBar.cshtml
@model _20170328prework.ViewModels.ToolBarViewModel

<div class="col-md-4 col-md-offset-8" id="toolbar">
    <nav>
        <ul class="list-inline">
            <li style="padding:0px">
                <button class="btn btn-warning" onclick="ToolBtnClick('Search')" id="Search" disabled="@(Model.DisSearch ?? false)" data-userstate="@(Model.DisSearch ?? false)" data-url="@Url.Action("Search",Model.ControllerName)" data-display="searchpanel">查詢</button>
            </li><!--
            --><li style="padding:0px">
                   <button class="btn btn-danger" onclick="ToolBtnClick('Add')" id="Add" disabled="@(Model.DisNew ?? false)" data-userstate="@(Model.DisNew ?? false)" data-url="@Url.Action("Add",Model.ControllerName)" data-display="display">新增</button>
            </li><!--
            --><li style="padding:0px">
                   <a class="btn btn-default" id="Check" disabled="@(Model.DisCheck ?? false)" data-userstate="@(Model.DisCheck ?? false)" href="@Url.Action("Check",Model.ControllerName)">確認</a>
            </li><!--
            --><li style="padding:0px">
                   <a class="btn btn-info" id="Delete" disabled="@(Model.DisDelete ?? false)" data-userstate="@(Model.DisDelete ?? false)" href="@Url.Action("Delete",Model.ControllerName)">刪除</a>
            </li><!-- 
            --><li style="padding:0px">
                   <a class="btn btn-success" id="Failed" disabled="@(Model.DisFailed ?? false)" data-userstate="@(Model.DisFailed ?? false)" href="@Url.Action("Failed",Model.ControllerName)">作廢</a>
            </li><!--            
            --><li style="padding:0px">
                   <a class="btn btn-primary" id="Attachment" disabled="@(Model.DisAttach ?? false)" data-userstate="@(Model.DisAttach ?? false)" href="@Url.Action("Attachment",Model.ControllerName)">附件</a>
            </li>
        </ul>
    </nav>
</div>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4><strong>查詢</strong></h4>
            </div>
            <div class="modal-body" id="searchpanel">

            </div>
        </div>
    </div>
</div>